# Generated by Django 6.0.7 on 2026-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("from_number", models.CharField(max_length=30)),
                ("message_body", models.TextField()),
                ("reply_sent", models.TextField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="WhatsAppLog",
        ),
    ]
