# Generated by Django 6.0.7 on 2026-07-27 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_tier", models.CharField(max_length=200)),
                ("available_quantity", models.PositiveIntegerField()),
                ("total_quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sales_start_at", models.DateTimeField()),
                ("sales_ended_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_to_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["sales_start_at", "price"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("purchased", "Purchased"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="ticket_qrcodes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.tickettype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_quantity__lte", models.F("total_quantity"))
                ),
                name="avalible_quantity_to_total_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="price_gte_zero"
            ),
        ),
    ]
